extends Node

signal entraPlayer(body, titulo, state)
signal clickShowcase()
signal removeGrabObject()
signal positionGrabObject(position, rotation, scale)
signal infoShowcase()
signal cierraShowcase()
signal meteObjeto(object_name)
signal seteaTempAttributes()
signal sendText(texto)
signal inConv(in_conv, parent_conv_name)
signal inMenu(in_menu)
signal nightStarts()
signal dayStarts()
signal clickedObjeto(object_name)
signal spookeado(_spookeado)
